[build]
  command = "npm install"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "18" 